version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Performing npm install"
      - npm install

  build:
    commands:
      - echo build started on 'date'
      - echo "Running npm build"
      - npm run build

artifacts:
  files: '**/*'

cache:
  paths:
    - "node_modules/**/*"
