version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Performing npm install"
      - npm install

  build:
    commands:
      - echo "Running npm build"
      - npm run build

artifacts:
  files: '**/*'
  base-directory: 'build'
  discard-paths: yes

cache:
  paths:
    - "node_modules/**/*"
